on: push

env:
  CTEST_OUTPUT_ON_FAILURE: 1
  CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

name: GCC

jobs:
  Build:
    runs-on: ${{ matrix.config.os }}
    name: ${{ matrix.config.os }}, ${{ matrix.config.compiler }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - { os: ubuntu-18.04, compiler_name: g++, compiler: g++-7, run: g++-7 }
          - { os: ubuntu-18.04, compiler_name: g++, compiler: g++-8, run: g++-8 }
          - { os: ubuntu-18.04, compiler_name: g++, compiler: g++-9, run: g++-9 }
          - { os: ubuntu-18.04, compiler_name: g++, compiler: g++-10, run: g++-10 }
          - { os: ubuntu-20.04, compiler_name: g++, compiler: g++-7, run: g++-7 }
          - { os: ubuntu-20.04, compiler_name: g++, compiler: g++-8, run: g++-8 }
          - { os: ubuntu-20.04, compiler_name: g++, compiler: g++-9, run: g++-9 }
          - { os: ubuntu-20.04, compiler_name: g++, compiler: g++-10, run: g++-10 }
    env:
      CXX: ${{ matrix.config.run }}

    steps:
      - uses: actions/checkout@v2

      - name: GCC
        run: |
          sudo apt-get update -y
          sudo apt-get install ${{ matrix.config.compiler }} -y

      - name: CMake
        uses: jwlawson/actions-setup-cmake@v1.0

      - name: Test
        run: |
          rm -rf build
          mkdir build
          cd build
          cmake .. && cmake --build .
          ctest --output-on-failure
          
      - name: Collect Code Coverage
        run: bash <(curl -s https://codecov.io/bash) -x gcov-9 || echo "Codecov did not collect coverage reports"
