name: MacOS

on: [push]

env:
  CTEST_OUTPUT_ON_FAILURE: 1

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - name: Get latest CMake
        uses: lukka/get-cmake@latest

      - name: Build and Test
        run: |
          cmake -Htest -Bbuild -DENABLE_TEST_COVERAGE=1
          cmake --build build --config Debug -j4
          ctest --build-config Debug
