name: MacOS

on: [push]

env:
  CTEST_OUTPUT_ON_FAILURE: 1

jobs:
  apple-clang:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v1

      - name: Build and Install
        run: |
          cmake -H. -Bbuild -DCMAKE_BUILD_TYPE=Release
          sudo cmake --build build --target install
          rm -rf build

      - name: Configure
        run: cmake -Htest -Bbuild

      - name: Build
        run: cmake --build build --config Debug -j4

      - name: Test
        run: |
          cd build
          ctest --build-config Debug
