name: MacOS

on: [push]

env:
  CTEST_OUTPUT_ON_FAILURE: 1

jobs:
  macos:
    runs-on: macos-latest
    env:
      CC: clang
      CXX: clang++

    steps:
      - uses: actions/checkout@v2

      - name: Set Xcode 11.6
        run: |
          sudo xcode-select -s /Applications/Xcode_11.6.app/Contents/Developer
          clang -v

      - name: Build and Test
        run: |
          cmake -Htest -Bbuild -DENABLE_TEST_COVERAGE=1
          cmake -Htest -Bbuild/test 
          cmake --build build --config Debug -j4
          cd build
          ctest --build-config Debug
