name: MacOS

on: [push]

env:
  CTEST_OUTPUT_ON_FAILURE: 1

jobs:
  apple-clang:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build and Test
        run: |
          cmake -H. -Bbuild -DCMAKE_BUILD_TYPE=Release
          cmake -Htest -Bbuild -DENABLE_TEST_COVERAGE=1
          cmake -Htest -Bbuild/test 
          cmake --build build --config Debug -j4
          cd build
          ctest --build-config Debug
