name: MinGW

on: push

jobs:
  windows-mingw:
    name: ${{ matrix.arch }}
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        mingw: ["32bit", "64bit"]
    env:
      CMAKE_GENERATOR: Ninja
      CC: gcc
      CXX: g++

    steps:
      - uses: actions/checkout@v2

      - name: Setup Scoop
        shell: powershell
        run: |
          Invoke-Expression (New-Object System.Net.WebClient).DownloadString('https://get.scoop.sh')
          scoop install sudo --global
          sudo scoop install git --global
          sudo scoop install ninja --global
          sudo scoop install cmake --global
          sudo scoop install gcc --arch #{{ matrix.mingw }} --global
          $env:path

      - name: Build and Test
        shell: powershell
        run: |
          $ENV:PATH="C:\ProgramData\scoop\shims;C:\ProgramData\scoop\apps\gcc\current\bin;C:\ProgramData\scoop\apps\ninja\current;$ENV:PATH"
          cmake -Htest -Bbuild -DENABLE_TEST_COVERAGE=1
          cmake --build build --config Debug -j4
