name: MinGW

on: push

env:
  CTEST_OUTPUT_ON_FAILURE: 1

jobs:
  windows-mingw:
    name: ${{ matrix.mingw }}
    runs-on: windows-latest
    env:
      CMAKE_GENERATOR: Ninja
      CC: gcc
      CXX: g++

    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        id: cache
        with:
          path: |
            C:\ProgramData\scoop
          key: scoop

      - name: Setup Scoop
        shell: powershell
        run: |
          Invoke-Expression (New-Object System.Net.WebClient).DownloadString('https://get.scoop.sh')
          scoop install sudo --global
          sudo scoop install git --global
          sudo scoop install ninja --global
          sudo scoop install cmake --global
          sudo scoop install gcc --arch 64bit --global
          $env:path

      - name: Build and Test
        shell: powershell
        run: |
          $ENV:PATH="C:\ProgramData\scoop\shims;C:\ProgramData\scoop\apps\gcc\current\bin;C:\ProgramData\scoop\apps\ninja\current;$ENV:PATH"
          cmake -Htest -Bbuild -DENABLE_TEST_COVERAGE=1
          cmake -Htest -Bbuild/test 
          cmake --build build --config Debug -j4
          cd build
          ctest --build-config Debug
