name: MinGW

on: push

jobs:
  windows-mingw:
    name: ${{ matrix.mingw }}
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        mingw: ["MINGW32", "MINGW64"]
    env:
      CMAKE_GENERATOR: Ninja
      CC: gcc
      CXX: g++

    steps:
      - uses: actions/checkout@v2

      - name: Setup Windows # This should almost never run if the cache works.
        if: steps.cache.outputs.cache-hit != 'true'
        shell: powershell
        run: |
          Invoke-Expression (New-Object System.Net.WebClient).DownloadString('https://get.scoop.sh')
          scoop install sudo --global
          sudo scoop install git --global
          sudo scoop install ninja --global
          sudo scoop install cmake --global
          sudo scoop install gcc --arch 64bit --global
          $env:path

      - name: Build and Test 64-bit x64
        shell: powershell
        run: |
          $ENV:PATH="C:\ProgramData\scoop\shims;C:\ProgramData\scoop\apps\gcc\current\bin;C:\ProgramData\scoop\apps\ninja\current;$ENV:PATH"
          cmake -Htest -Bbuild -DENABLE_TEST_COVERAGE=1
          cmake --build build --config Debug -j4

      - name: collect code coverage
        run: bash <(curl -s https://codecov.io/bash) -x gcov-9 || echo "Codecov did not collect coverage reports"
